# See https://robots.thoughtbot.com/configure-travis-ci-for-go
language: go
sudo: false
before_script:
  - bin/vet
install:
  # Add Godeps dependencies to GOPATH and PATH
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
